# =============================
# Unified dependency config for MCDSL
# =============================

[python]
version = "3.12"

[mcdsl]
version = "0.1.0"

[modloaders]

# Fabric
[modloaders.fabric]
version = "1.21.10"
hot_reload = true

# Forge
[modloaders.forge]
version = "47.1.0"
hot_reload = false

# Quilt
[modloaders.quilt]
version = "1.20.5"
hot_reload = true
